# Generated by Django 4.1.7 on 2023-03-11 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "assignmentid",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("score", models.IntegerField()),
                ("quiz_due", models.DateTimeField()),
                ("assignment_file", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("classid", models.IntegerField(primary_key=True, serialize=False)),
                ("class_time", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("courseid", models.IntegerField(primary_key=True, serialize=False)),
                ("course_name", models.CharField(max_length=50)),
                ("course_type", models.CharField(max_length=10)),
                ("course_year", models.IntegerField()),
                ("course_term", models.IntegerField()),
                ("course_number", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("studentid", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=255)),
                ("medal", models.CharField(max_length=255)),
                ("profile_photo", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("staffid", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=255)),
                ("profile_photo", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="Wt_Ass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_file", models.CharField(max_length=255)),
                ("mark", models.IntegerField()),
                ("feedback", models.CharField(max_length=255)),
                (
                    "assignmentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainpage.assignment",
                    ),
                ),
                (
                    "studentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainpage.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("quizid", models.IntegerField(primary_key=True, serialize=False)),
                ("quizname", models.CharField(max_length=50)),
                ("quiz_due", models.DateTimeField()),
                ("quiz_trytime", models.IntegerField()),
                ("quiz_file", models.BinaryField()),
                ("answer_file", models.CharField(max_length=255)),
                ("score", models.IntegerField()),
                (
                    "courseid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainpage.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("materialid", models.IntegerField(primary_key=True, serialize=False)),
                ("material_type", models.CharField(max_length=255)),
                ("material_importance", models.CharField(max_length=255)),
                ("material_name", models.CharField(max_length=255)),
                ("material_path", models.CharField(max_length=255)),
                (
                    "courseid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainpage.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="courseid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainpage.course"
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark", models.IntegerField()),
                (
                    "quizid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainpage.quiz"
                    ),
                ),
                (
                    "studentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainpage.student",
                    ),
                ),
            ],
        ),
    ]
